language: node_js
node_js:
  - "6"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: PUqHW83Ad2U8bDWotRcPycWKeZoTHgBVx5Hz1hydYvdSPgx4u04Hg9/vg+DGU7hRSn8B6y+mWajL8WMhdlcKo3NqfSXpFn0jEoMgzeQHXJkyx8qjqfBuaMcoogDRFvkzi+sEu/ObjaL9WyAxIZDPa69ZMylUh0KjsDqoMtQXrEgamRVz4ADTUkLWNqa4bbGbRjbuGWNtCpUgFXGBEtCnpi/N38uS1mtKtXpNCGZ2gB0b930YrXldWYW9a10aSuSvpWlglzgN1ZW9TwGlXjKz3oR/nWBVgRi/VSvaN4WzKU/CVbyYPwiQYCbdNUVDtpfdZQKam74AVS500InL/y8rFYPsOjFqDd8FjtWU5+F5vFkzfFHk8DO+OekQrC/CabKSM8f3ah3z5Wjv4mkGGw5HBcxGLkLe5ix2HxuMXkz8Fs+eHxeDMvMwKddmGlMJFFzY5nQ7xxVztM3O7/euMPEkysHOes7BUHMNWbZ9H6SpHYb3xuQaFUrsVxlpVRcO+VhWLP+ujYnz5pNSOLjYB3m5KrCs3xkORnsn4jQ1GLPCl7rRUm3lmt0MwsmSyImDOsjEcJ46IgGXnSfrgXmnCEyHQV86SB1OXsoJW96kzgy/oi8ca9ht/SglGjPgrVyv651WPWxZn/ZJQH3y7rYj+YIlZu28m6mUaWAJCobG+ly1V5Q=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh

before_script:
- npm test

script:
- npm run data

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}