# https://github.com/developmentseed/how/issues/149
# ssh-keygen -m pem -t rsa -b 4096 -C AMT-Autoridade/taxis -f deploy_key
version: 2
jobs:
  build:
    docker:
      - image: node:6

    working_directory: ~/repo

    environment:
      - PRODUCTION_BRANCH: master
      - GH_REF: git@github.com:AMT-Autoridade/taxis.git
      - GH_NAME: "Major"
      - GH_EMAIL: "ci@wegomajor.com"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - add_ssh_keys:
          fingerprints:
            - "e8:96:06:fa:0f:a8:b7:31:67:cb:4f:e5:ab:70:2d:bb"

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              yarn data
            else
              echo "Skip processing data"
            fi

      - run:
          name: Deploy to GH
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              mkdir dist
              mv ./export/*.json dist
              mv ./files dist
              cd dist
              git init
              git config user.name "$GH_NAME"
              git config user.email "$GH_EMAIL"
              git add .
              git commit -m "CI deploy [skip ci]"
              git remote add origin $GH_REF
              git push origin --force --quiet HEAD:api
              rm -rf .git
            else
              echo "Skip deploying to Github"
            fi